### PR TITLE
Added is system to gateway requests

### PR DESCRIPTION
**Pull request by dylanratcliffe**

### CODE REVIEW

**Review by getinnocuous — APPROVED** [review]

**Review by DavidS-ovm — COMMENTED** [review]
what's prompting us to expose that to the public?

**Comment by dylanratcliffe** [comment]
Good catch I've got this wrong. That should be for bookmarks not snapshots. The reason I'm exposing it is that we can then have the "Share" button create a system bookmark that doesn't show up in list calls. If we want to add other bookmarks to that account in the future, all the ones created with "Share" won't pollute that list

**Comment by dylanratcliffe** [comment]
Gah and it's already there for bookmarks! Derp

**Comment by DavidS-ovm** [comment]
Let's leave this here then to keep the two in sync.

**Comment by dylanratcliffe** [comment]
Nah snapshots don't have an `isSystem` property, only bookmarks, since there isn't anywhere that we actually list snapshots so they are kind of already "system"

**Pull request merged**
