### PR TITLE
Added API Endpoints for account config

### PR DESCRIPTION
**Pull request by DavidS-ovm**
This is where we will store config like the blast radius limits.

Supersedes https://github.com/overmindtech/sdp/pull/224, relates to https://github.com/overmindtech/api-server/issues/953

### CODE REVIEW

**Comment by DavidS-ovm** [comment]
@dylanratcliffe rewrote your content from #224 to go where it was supposed to. the `config.proto` will also be the home for future user-specific configs, and it'll do us well to keep everything that's working in that corner of the database in one location.

Feel free to merge if you're happy with this.

**Review by dylanratcliffe — APPROVED** [review]

**Comment by DavidS-ovm** [comment]
This needed a bunch more work because I originally named the proto package `cli`, which doesn't make sense now anymore. So this became a lot more juggling than expected...

**Comment by dylanratcliffe** [comment]
@DavidS-ovm Are you able to create the tickets required to migrate this? Changing the package name will require quite a lot of cleanup, and maybe a redirect or something in the server since the endpoint name will change and will break old versions of the CLI

**Comment by DavidS-ovm** [comment]
@dylanratcliffe created https://github.com/overmindtech/cli/issues/414 for a high-level overview of what needs to happen.

**Pull request merged**
